#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-shoulda-context
Version  : 1.2.1
Release  : 3
URL      : https://rubygems.org/downloads/shoulda-context-1.2.1.gem
Source0  : https://rubygems.org/downloads/shoulda-context-1.2.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-shoulda-context-bin
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-rails
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubygems-tasks
BuildRequires : rubygem-test-unit

%description
# shoulda-context [![Gem Version](https://badge.fury.io/rb/shoulda-context.png)](http://badge.fury.io/rb/shoulda-context) [![Build Status](https://travis-ci.org/thoughtbot/shoulda-context.png?branch=master)](https://travis-ci.org/thoughtbot/shoulda-context)

%package bin
Summary: bin components for the rubygem-shoulda-context package.
Group: Binaries

%description bin
bin components for the rubygem-shoulda-context package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n shoulda-context-1.2.1
gem spec %{SOURCE0} -l --ruby > rubygem-shoulda-context.gemspec

%build
gem build rubygem-shoulda-context.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
shoulda-context-1.2.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/shoulda-context-1.2.1.gem
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/DuplicateTestError/cdesc-DuplicateTestError.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Proc/cdesc-Proc.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Proc/object;/cdesc-object;.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/Assertions/assert_accepts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/Assertions/assert_contains-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/Assertions/assert_does_not_contain-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/Assertions/assert_rejects-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/Assertions/assert_same_elements-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/Assertions/cdesc-Assertions.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/Assertions/safe_assert_block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/ClassMethods/before_should-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/ClassMethods/context-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/ClassMethods/described_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/ClassMethods/should-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/ClassMethods/should_eventually-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/ClassMethods/should_not-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/ClassMethods/subject-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/Context/cdesc-Context.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/InstanceMethods/cdesc-InstanceMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/InstanceMethods/construct_subject-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/InstanceMethods/subject-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/TestFrameworkDetection/cdesc-TestFrameworkDetection.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/TestFrameworkDetection/detected_test_framework_test_cases-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/TestFrameworkDetection/possible_test_frameworks-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/TestFrameworkDetection/resolve_framework-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/TestFrameworkDetection/test_framework_test_cases-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/cdesc-Context.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/contexts-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/Context/test_framework_test_cases-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/Shoulda/cdesc-Shoulda.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/ShouldaContextLoadable/cdesc-ShouldaContextLoadable.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/ShouldaContextLoadable/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/lib/shoulda/context/tasks/page-list_tests_rake.ri
/usr/lib64/ruby/gems/2.2.0/doc/shoulda-context-1.2.1/ri/lib/shoulda/context/tasks/page-yaml_to_shoulda_rake.ri
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/.ruby-version
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/Appraisals
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/MIT-LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/README.md
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/bin/convert_to_should_syntax
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/gemfiles/minitest_4_x.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/gemfiles/minitest_4_x.gemfile.lock
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/gemfiles/minitest_5_x.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/gemfiles/minitest_5_x.gemfile.lock
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/gemfiles/rails_3_0.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/gemfiles/rails_3_0.gemfile.lock
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/gemfiles/rails_3_1.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/gemfiles/rails_3_1.gemfile.lock
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/gemfiles/rails_3_2.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/gemfiles/rails_3_2.gemfile.lock
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/gemfiles/rails_4_0.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/gemfiles/rails_4_0.gemfile.lock
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/gemfiles/rails_4_1.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/gemfiles/rails_4_1.gemfile.lock
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/gemfiles/test_unit.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/gemfiles/test_unit.gemfile.lock
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/init.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda-context.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/assertions.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/autoload_macros.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/proc_extensions.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/tasks.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/tasks/list_tests.rake
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/tasks/yaml_to_shoulda.rake
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/test_framework_detection.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/lib/shoulda/context/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/rails/init.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/shoulda-context.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/tasks/shoulda.rake
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/test/fake_rails_root/test/shoulda_macros/custom_macro.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/test/fake_rails_root/vendor/gems/gem_with_macro-0.0.1/shoulda_macros/gem_macro.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/test/fake_rails_root/vendor/plugins/.keep
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/test/fake_rails_root/vendor/plugins/plugin_with_macro/shoulda_macros/plugin_macro.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/test/shoulda/autoload_macro_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/test/shoulda/context_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/test/shoulda/convert_to_should_syntax_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/test/shoulda/helpers_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/test/shoulda/should_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/test/shoulda/test_framework_detection_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/shoulda-context-1.2.1/test/test_helper.rb
/usr/lib64/ruby/gems/2.2.0/specifications/shoulda-context-1.2.1.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/convert_to_should_syntax
